name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build web assets
        run: npm run build

      - name: Sync Capacitor Android
        run: npx cap sync android

      - name: Setup Java (required for Android build)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission to gradlew
        working-directory: android
        run: chmod +x gradlew

      - name: Build Android APK (Debug)
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: moodmirror-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

